create_clock -period 10.000 -name clk_100 -waveform {0.000 5.000} [get_ports clk_100]
create_clock -name rmii_clocks_ref_clk -period 20.0 [get_ports rmii_clocks_ref_clk]

set_property IOSTANDARD LVCMOS33 [get_ports clk_100]
set_property PACKAGE_PIN N15 [get_ports clk_100]

set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN J2 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports capture]
set_property PACKAGE_PIN J1 [get_ports capture]

set_property IOSTANDARD LVCMOS33 [get_ports write_btn]
set_property PACKAGE_PIN G2 [get_ports write_btn]



#PHY Signals
set_property IOSTANDARD LVCMOS33 [get_ports rmii_clocks_ref_clk]
set_property PACKAGE_PIN G16 [get_ports rmii_clocks_ref_clk]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rmii_clocks_ref_clk_IBUF]
set_property IOSTANDARD LVCMOS33 [get_ports rmii_crs_dv]
set_property PACKAGE_PIN J16 [get_ports rmii_crs_dv]
set_property IOSTANDARD LVCMOS33 [get_ports rmii_mdc]
set_property PACKAGE_PIN J15 [get_ports rmii_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports rmii_mdio]
set_property PACKAGE_PIN M14 [get_ports rmii_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports {rmii_rx_data[0]}]
set_property PACKAGE_PIN L17 [get_ports {rmii_rx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rmii_rx_data[1]}]
set_property PACKAGE_PIN K14 [get_ports {rmii_rx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rmii_tx_data[0]}]
set_property PACKAGE_PIN K16 [get_ports {rmii_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rmii_tx_data[1]}]
set_property PACKAGE_PIN N14 [get_ports {rmii_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports rmii_tx_en]
set_property PACKAGE_PIN L18 [get_ports rmii_tx_en]

set_false_path -quiet -to [get_nets -filter {mr_ff == TRUE}]
set_false_path -quiet -to [get_pins -filter {REF_PIN_NAME == PRE} -of_objects [get_cells -hierarchical -filter {ars_ff1 == TRUE || ars_ff2 == TRUE}]]
set_max_delay 2 -quiet -from [get_pins -filter {REF_PIN_NAME == Q} -of_objects [get_cells -hierarchical -filter {ars_ff1 == TRUE}]] -to [get_pins -filter {REF_PIN_NAME == D} -of_objects [get_cells -hierarchical -filter {ars_ff2 == TRUE}]]
set_clock_groups -group [get_clocks -include_generated_clocks -of [get_nets clk_100]] -group [get_clocks -include_generated_clocks -of [get_ports rmii_clocks_ref_clk]] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks -of [get_ports rmii_clocks_ref_clk]] -group [get_clocks -include_generated_clocks -of [get_nets clk_100]] -asynchronous
###set_property CLOCK_BUFFER_TYPE BUFG [get_nets rmii_clocks_ref_clk]



#Camera Signals
set_property IOSTANDARD LVCMOS33 [get_ports c_SDA]
set_property PACKAGE_PIN H18 [get_ports c_SDA]
set_property PULLTYPE PULLUP [get_ports c_SDA]

set_property IOSTANDARD LVCMOS33 [get_ports c_SCL]
set_property PACKAGE_PIN H16 [get_ports c_SCL]
set_property PULLTYPE PULLUP [get_ports c_SCL]

set_property IOSTANDARD LVCMOS33 [get_ports c_HS]
set_property PACKAGE_PIN E16 [get_ports c_HS]
set_property IOSTANDARD LVCMOS33 [get_ports c_VS]
set_property PACKAGE_PIN G18 [get_ports c_VS] 
set_property IOSTANDARD LVCMOS33 [get_ports c_XLK]
set_property PACKAGE_PIN C11 [get_ports c_XLK]
set_property IOSTANDARD LVCMOS33 [get_ports c_PLK]
set_property PACKAGE_PIN C12 [get_ports c_PLK]
set_property IOSTANDARD LVCMOS33 [get_ports c_PWDN]
set_property PACKAGE_PIN D11 [get_ports c_PWDN]
set_property IOSTANDARD LVCMOS33 [get_ports c_RET]
set_property PACKAGE_PIN D10 [get_ports c_RET]

set_property IOSTANDARD LVCMOS33 [get_ports {c_D[0]}]
set_property PACKAGE_PIN F14 [get_ports {c_D[0]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {c_D[1]}]
set_property PACKAGE_PIN J13 [get_ports {c_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {c_D[2]}]
set_property PACKAGE_PIN F15 [get_ports {c_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {c_D[3]}]
set_property PACKAGE_PIN J14 [get_ports {c_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {c_D[4]}]
set_property PACKAGE_PIN H13 [get_ports {c_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {c_D[5]}]
set_property PACKAGE_PIN E14 [get_ports {c_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {c_D[6]}]
set_property PACKAGE_PIN H14 [get_ports {c_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {c_D[7]}]
set_property PACKAGE_PIN E15 [get_ports {c_D[7]}]



#HDMI Signals
set_property -dict {PACKAGE_PIN U16 IOSTANDARD TMDS_33} [get_ports hdmi_clk_p]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD TMDS_33} [get_ports hdmi_clk_n]

set_property -dict {PACKAGE_PIN U18 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[0]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[1]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_n[2]}]

set_property -dict {PACKAGE_PIN U17 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[0]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[1]}]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD TMDS_33} [get_ports {hdmi_tx_p[2]}]



#Switches
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_i[0]}]

set_property PACKAGE_PIN G1 [get_ports {sw_i[0]}]
set_property PACKAGE_PIN F2 [get_ports {sw_i[1]}]
set_property PACKAGE_PIN F1 [get_ports {sw_i[2]}]
set_property PACKAGE_PIN E2 [get_ports {sw_i[3]}]
set_property PACKAGE_PIN E1 [get_ports {sw_i[4]}]
set_property PACKAGE_PIN D2 [get_ports {sw_i[5]}]
set_property PACKAGE_PIN D1 [get_ports {sw_i[6]}]
set_property PACKAGE_PIN C2 [get_ports {sw_i[7]}]
set_property PACKAGE_PIN B2 [get_ports {sw_i[8]}]
set_property PACKAGE_PIN A4 [get_ports {sw_i[9]}]
set_property PACKAGE_PIN A5 [get_ports {sw_i[10]}]
set_property PACKAGE_PIN A6 [get_ports {sw_i[11]}]
set_property PACKAGE_PIN C7 [get_ports {sw_i[12]}]
set_property PACKAGE_PIN A7 [get_ports {sw_i[13]}]
set_property PACKAGE_PIN B7 [get_ports {sw_i[14]}]
set_property PACKAGE_PIN A8 [get_ports {sw_i[15]}]



#7 segment displays
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_a[0]}]
set_property PACKAGE_PIN G6 [get_ports {hex_grid_a[0]}]
set_property PACKAGE_PIN H6 [get_ports {hex_grid_a[1]}]
set_property PACKAGE_PIN C3 [get_ports {hex_grid_a[2]}]
set_property PACKAGE_PIN B3 [get_ports {hex_grid_a[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_a[0]}]
set_property PACKAGE_PIN E6 [get_ports {hex_seg_a[0]}]
set_property PACKAGE_PIN B4 [get_ports {hex_seg_a[1]}]
set_property PACKAGE_PIN D5 [get_ports {hex_seg_a[2]}]
set_property PACKAGE_PIN C5 [get_ports {hex_seg_a[3]}]
set_property PACKAGE_PIN D7 [get_ports {hex_seg_a[4]}]
set_property PACKAGE_PIN D6 [get_ports {hex_seg_a[5]}]
set_property PACKAGE_PIN C4 [get_ports {hex_seg_a[6]}]
set_property PACKAGE_PIN B5 [get_ports {hex_seg_a[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_grid_b[0]}]
set_property PACKAGE_PIN E4 [get_ports {hex_grid_b[0]}]
set_property PACKAGE_PIN E3 [get_ports {hex_grid_b[1]}]
set_property PACKAGE_PIN F5 [get_ports {hex_grid_b[2]}]
set_property PACKAGE_PIN H5 [get_ports {hex_grid_b[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hex_seg_b[0]}]
set_property PACKAGE_PIN F3 [get_ports {hex_seg_b[0]}]
set_property PACKAGE_PIN G5 [get_ports {hex_seg_b[1]}]
set_property PACKAGE_PIN J3 [get_ports {hex_seg_b[2]}]
set_property PACKAGE_PIN H4 [get_ports {hex_seg_b[3]}]
set_property PACKAGE_PIN F4 [get_ports {hex_seg_b[4]}]
set_property PACKAGE_PIN H3 [get_ports {hex_seg_b[5]}]
set_property PACKAGE_PIN E5 [get_ports {hex_seg_b[6]}]
set_property PACKAGE_PIN J4 [get_ports {hex_seg_b[7]}]